

#Load all of our ActiveRecord::Base objects
require_relative './author.rb' #authors table
require_relative './publisher.rb' #publishers table
require_relative './language.rb' #languages table
require_relative './genre.rb' #genres tables
require_relative './book.rb' #books tables
require_relative './book_author.rb' #books_authors tables

# Establish our connection to our serverless sqlite3 database.
ActiveRecord::Base.establish_connection :adapter => 'sqlite3', :database => 'db/development.sqlite3'

# For debugging purposes, uncomment this line to see the SQL generated by ActiveRecord:
ActiveRecord::Base.logger = Logger.new(STDOUT)